drop table stock_id_clients;
CREATE TABLE stock_id_clients(
	IDCLIENT INTEGER PRIMARY KEY,
	IDREP VARCHAR(30),
	NOM VARCHAR(30),
	PRENOM VARCHAR(30),
	USERNAME VARCHAR(30),
	BIRTHDAY DATE,
	LAST_LOGIN DATE,
	SECURE_KEY VARCHAR(30),
	PRICING_PLAN VARCHAR(30)
);
